apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-cluster-member
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.1
  authSecret: varahamihir-couchbase-operator-secret
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: True
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: False
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 256
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  securityContext:
    fsGroup: 1000
  servers:
    - size: 3
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      pod:
        volumeMounts:
          default: couchbase
          data:  couchbase
          index: couchbase
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: default-varahamihir-couchbase-operator-storeclass-819d
        resources:
          requests:
            storage: 3Gi
