apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
spec:
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      serviceAccountName: varahamihir-ksa
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        name: identity-server
        image: "gcr.io/varahamihir-cloud/identity-server:0.0.1-SNAPSHOT"
        imagePullPolicy: "Always"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8081
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "identity-server"
        ports:
        - containerPort: 8081
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8081
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10

        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: varahamihir-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: varahamihir-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: varahamihir-secret
              key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command: [ "/cloud_sql_proxy",  "-instances=varahamihir-cloud:us-central1:varahamihir-sql=tcp:3306", "-ip_address_types=PRIVATE" ]
        securityContext:
          runAsNonRoot: true
