apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-sample
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: varahamihir-gsa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:varahamihir-cloud.svc.id.goog[varahamihir-k8s-ns/varahamihir-ksa-name]
