# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: lessons
  name: lessons
spec:
  replicas: 1
  selector:
    matchLabels:
      run: lessons-exposed
  template:
    metadata:
      labels:
        run: lessons-exposed
    spec:
      serviceAccountName: chaos
      containers:
        - image: varahamihir/lessons
          name: lessons
          ports:
            - containerPort: 8070
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: lessons
  name: lessons
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8070
  selector:
    run: lessons-exposed
  type: NodePort