spring:
  cloud:
    gateway:
      #      default-filters:
      #        - name: SCGWGlobalFilter
      routes:
        - id: identity-server
          uri: lb://identity-server-87prb:8081/
          predicates:
            - Path=/*/user/**
            - Path=/*/tenant/**
          filters:
            - name: VarahamihirGatewayRequestPreFilter
            - name: VarahamihirGatewayRequestPostFilter
