# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: guardian
  name: guardian
spec:
  replicas: 1
  selector:
    matchLabels:
      run: guardian-exposed
  template:
    metadata:
      labels:
        run: guardian-exposed
    spec:
      serviceAccountName: chaos
      containers:
        - image: varahamihir/guardian
          name: guardian
          ports:
            - containerPort: 8070
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: guardian
  name: guardian
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8070
  selector:
    run: gateway-exposed
  type: NodePort